recipe("water", "water", "puddle");
recipe("water", "fire", "steam");
recipe("water", "air", "mist");
recipe("water", "earth", "mud");
recipe("puddle", "puddle", "pool");
recipe("mud", "earth", "clay");
recipe("clay", "fire", "brick");
recipe("earth", "life", "soil");
recipe("earth", "earth", "rock");
recipe("rock", "fire", "lava");
recipe("pool", "pool", "pond");
recipe("pond", "pond", "lake");
recipe("lake", "lake", "bay");
recipe("bay", "bay", "sea");
recipe("sea", "sea", "ocean");
recipe("air", "mist", "cloud");
recipe("rock", "rock", "boulder");
recipe("boulder", "boulder", "hill");
recipe("hill", "hill", "mountain");
recipe("mountain", "lava", "volcano");
recipe("mountain", "mountain", "mountain range");
recipe("mountain range", "mountain range", "continent");
recipe("continent", "ocean", "planet");
recipe("brick", "brick", "wall");
recipe("wall", "wall", "house");
recipe("house", "house", "street");
recipe("street", "street", "neighborhood");
recipe("neighborhood", "neighborhood", "village");
recipe("village", "village", "town");
recipe("town", "town", "city");
recipe("city", "city", "metropolis");
recipe("metropolis", "metropolis", "megacity");
recipe("megacity", "megacity", "conurbation");
recipe("conurbation", "conurbation", "megaregion");
recipe("megaregion", "megaregion", "eperopolis");
recipe("eperopolis", "eperopolis", "ecumenopolis");
recipe("cloud", "water", "rain");
recipe("air", "air", "pressure");
recipe("lava", "water", "obsidian");
recipe("volcano", "water", "geyser");
recipe("volcano", "ocean", "island");
recipe("island", "island", "archipelago");
recipe("continent", "continent", "supercontinent");
recipe("planet", "planet", "solar system");
recipe("house", "fire", "hearth");
recipe("village", "wall", "fort");
recipe("fort", "house", "fortress");
recipe("fortress", "fortress", "castle");
recipe("castle", "castle", "palace");
recipe("hill", "water", "valley");
recipe("mountain", "lake", "alpine lake");
recipe("mountain range", "sea", "fjord");
recipe("mist", "mist", "fog");
recipe("fog", "fog", "cloud");
recipe("steam", "fire", "smoke");
recipe("soil", "house", "garden");
recipe("air", "earth", "dust");
recipe("dust", "rain", "acid rain");
recipe("dust", "fire", "gunpowder");
recipe("gunpowder", "pressure", "deflagration");
recipe("air", "planet", "atmosphere");
recipe("atmosphere", "mist", "cloud");
recipe("water", "planet", "hydrosphere");
recipe("fire", "gunpowder", "explosion");
recipe("explosion", "pressure", "overpressure");
recipe("steam engine", "explosion", "combustion engine");
recipe("earth", "cloud", "fog");
recipe("wall", "water", "dam");
recipe("fire", "fire", "energy");
recipe("energy", "steam", "steam engine");
recipe("energy", "gunpowder", "explosion");
recipe("energy", "air", "thermal energy");
recipe("ocean", "ocean", "pressure");
recipe("plant", "earth", "grass");
recipe("plant", "lake", "swamp");
recipe("plant", "pond", "reed");
recipe("hydrosphere", "energy", "primordial soup");
recipe("primordial soup", "energy", "life");
recipe("life", "water", "plankton");
recipe("life", "air", "aeroplankton");
recipe("life", "soil", "plant");
recipe("plant", "swamp", "cattail");
recipe("plant", "sea", "seaweed");
recipe("air", "lava", "stone");
recipe("stone", "air", "sand");
recipe("sand", "ocean", "beach");
recipe("sand", "fire", "glass");
recipe("mud", "sand", "clay");
recipe("clay", "life", "human");
recipe("human", "castle", "monarch");
recipe("fjord", "earth", "land");
recipe("monarch", "land", "country");
recipe("fire", "planet", "star");
recipe("country", "lake", "canada");
recipe("human", "canada", "canadian");
recipe("land", "land", "continent");
recipe("house", "glass", "greenhouse");
recipe("human", "house", "family");
recipe("life", "land", "animal");
recipe("animal", "air", "bird");
recipe("animal", "ocean", "fish");
recipe("animal", "lake", "fish");
recipe("animal", "sea", "fish");
recipe("fish", "glass", "aquarium");
recipe("aquarium", "land", "zoo");
recipe("zoo", "water", "aquarium");
recipe("zoo", "air", "aviary");
recipe("aviary", "land", "zoo");
recipe("brick", "fire", "kiln");
recipe("kiln", "kiln", "furnace");
recipe("kiln", "clay", "ceramic");
recipe("rain", "energy", "lightning");
recipe("lightning", "cloud", "storm cloud");
recipe("steam engine", "steam", "electricity");
recipe("electricity", "cloud", "thundercloud");
recipe("storm", "electricity", "thunderstorm");
recipe("sand", "glass", "hourglass");
recipe("solar system", "solar system", "galaxy");
recipe("galaxy", "galaxy", "galaxy group");
recipe("galaxy group", "galaxy group", "galaxy cluster");
recipe("galaxy cluster", "galaxy cluster", "galaxy supercluster");
recipe("galaxy supercluster", "galaxy supercluster", "galaxy filament");
recipe("galaxy filament", "galaxy filament", "universe");
recipe("universe", "universe", "multiverse");
recipe("universe", "human", "science");
recipe("science", "science", "technology");
recipe("science", "human", "scientist");
recipe("science", "technology", "technoscience");
recipe("electricity", "glass", "lightbulb");
recipe("lightbulb", "human", "idea");
recipe("idea", "human", "philosophy");
recipe("philosophy", "country", "ideology");
recipe("philosophy", "house", "container");
recipe("container", "electricity", "battery");
recipe("container", "energy", "battery");
recipe("battery", "water", "electrolysis");
recipe("life", "planet", "earth (planet)");
recipe("earth (planet)", "star", "sun");
recipe("sun", "plant", "photosynthesis");
recipe("photosynthesis", "plant", "oxygen");
recipe("photosynthesis", "plankton", "phytoplankton");
recipe("sun", "phytoplankton", "oxygen");
recipe("pressure", "plant", "coal");
recipe("coal", "pressure", "diamond");
recipe("hourglass", "philosophy", "time");
recipe("time", "plant", "tree");
recipe("stone", "lake", "ducks and drakes");
recipe("ducks and drakes", "stone", "drakestone");
recipe("ducks and drakes", "rock", "drakestone");
recipe("animal", "dam", "beaver");
recipe("wood", "pressure", "paper");
recipe("paper", "wood", "book");
recipe("book", "idea", "story");
recipe("fire", "wood", "campfire");
recipe("campfire", "smoke", "smoke signal");
recipe("wood", "tool", "wheel");
recipe("wheel", "wood", "cart");
recipe("wood", "water", "boat");
recipe("tree", "fire", "charcoal");
recipe("wood", "corpse", "coffin");
recipe("tree", "house", "treehouse");
recipe("wood", "tree", "stick");
recipe("stick", "fish", "fishing rod");
recipe("fishing rod", "fish", "angler fish");
recipe("stick", "idea", "weapon");
recipe("weapon", "gunpowder", "firearm");
recipe("wood", "wall", "fence");
recipe("wood", "human", "house");
recipe("house", "wood", "log cabin");
recipe("wood", "coal", "pencil");
recipe("wood", "charcoal", "pencil");
recipe("wood", "life", "puppet");
recipe("life", "corpse", "zombie");
recipe("zombie", "science", "necromancy");
recipe("time", "corpse", "skeleton");
recipe("necromancy", "human", "necromancer");
recipe("country", "skeleton", "mexico");
recipe("mexico", "human", "mexican");
recipe("tobacco", "wood", "pipe");
recipe("bird", "wood", "woodpecker");
recipe("wood", "container", "bucket");
recipe("wood", "pencil", "ruler");
recipe("plant", "fire", "tobacco");
recipe("plant", "smoke", "incense");
recipe("tobacco", "paper", "cigarette");
recipe("cigarette", "human", "lung cancer");
recipe("lung cancer", "human", "corpse");
recipe("corpse", "philosophy", "death");
recipe("tobacco", "country", "jamaica");
recipe("jamaica", "human", "jamaican");
recipe("cigarette", "plant", "cannabis");
recipe("country", "cigarette", "cuba");
recipe("cuba", "human", "cuban");
recipe("skeleton", "philosophy", "death");
recipe("philosophy", "human", "philosopher");
recipe("time", "life", "death");
recipe("bone", "corpse", "skeleton");
recipe("skeleton", "light", "x-ray");
recipe("lightbulb", "electricity", "light");
recipe("skeleton", "earth", "fossil");
recipe("skeleton", "rock", "fossil");
recipe("skeleton", "stone", "fossil");
recipe("skeleton", "time", "fossil");
recipe("fossil", "animal", "dinosaur");
recipe("electricity", "corpse", "frankenstein");
recipe("frankenstein", "science", "reanimation");
recipe("corpse", "earth", "grave");
recipe("grave", "grave", "graveyard");
recipe("grave", "necromancy", "zombie");
recipe("grave", "reanimation", "zombie");
recipe("grave", "life", "zombie");
recipe("bird", "corpse", "vulture");
recipe("vulture", "corpse", "skeleton");
recipe("corpse", "stone", "fossil");
recipe("corpse", "rock", "fossil");
recipe("atmosphere", "air", "sky");
recipe("sky", "star", "space");
recipe("space", "human", "astronaut");
recipe("sky", "sun", "day");
recipe("space", "glass", "telescope");
recipe("tree", "tool", "wood");
recipe("cloud", "energy", "storm");
recipe("tool", "woodpecker", "hammer");
recipe("hammer", "boulder", "ore");
recipe("wood", "earth", "plow");
recipe("plow", "earth", "field");
recipe("field", "human", "farmer");
recipe("human", "wood", "tool");
recipe("human", "rock", "tool");
recipe("human", "stone", "tool");
recipe("farmer", "animal", "livestock");
recipe("livestock", "grass", "cow");
recipe("livestock", "cloud", "sheep");
recipe("cloud", "animal", "sheep");
recipe("mud", "animal", "pig");
recipe("mud", "livestock", "pig");
recipe("livestock", "bird", "chicken");
recipe("sun", "day", "morning");
recipe("morning", "bird", "rooster");
recipe("morning", "chicken", "rooster");
recipe("cow", "water", "milk");
recipe("cow", "farmer", "milk");
recipe("cow", "house", "barn");
recipe("sea", "cow", "manatee");
recipe("cow", "human", "minotaur");
recipe("milk", "time", "cheese");
recipe("cheese", "animal", "mouse");
recipe("mouse", "sky", "bat");
recipe("bat", "house", "cave");
recipe("cave", "rock", "ore");
recipe("cow", "mountain", "yak");
recipe("sand", "sand", "desert");
recipe("desert", "cow", "camel");
recipe("human", "human", "love");
recipe("love", "time", "eternal");
recipe("love", "plant", "rose");
recipe("love", "container", "family");
recipe("love", "diamond", "ring");
recipe("ring", "love", "marriage");
recipe("marriage", "human", "wedding");
recipe("continent", "country", "australia");
recipe("australia", "human", "australian");
recipe("australia", "sun", "skin cancer");
recipe("skin cancer", "human", "corpse");
recipe("corpse", "flower", "titan arum");
recipe("plant", "garden", "flower");
recipe("plant", "fence", "hedge");
recipe("garden", "fence", "hedge");
recipe("time", "tool", "clock");
recipe("human", "tool", "engineer");
recipe("tool", "fish", "fishing rod");
recipe("tool", "light", "flashlight");
recipe("tool", "brick", "house");
recipe("tool", "grass", "lawn mower");
recipe("tool", "garden", "trowel");
recipe("grass", "garden", "weed");
recipe("weed", "tool", "weed whacker");
recipe("tool", "cow", "meat");
recipe("tool", "pig", "meat");
recipe("tool", "sheep", "wool");
recipe("clay", "tool", "pottery");
recipe("space", "water", "ice");
recipe("rain", "human", "cold");
recipe("cold", "water", "ice");
recipe("ice", "water", "glacier");
recipe("ice", "continent", "antarctica");
recipe("antarctica", "ocean", "arctic");
recipe("stone", "tool", "statue");
recipe("sheep", "plant", "cotton");
recipe("wool", "plant", "cotton");
recipe("cotton", "tool", "thread");
recipe("wool", "tool", "thread");
recipe("rain", "tool", "umbrella");
recipe("pressure", "tool", "boiler");
recipe("steam", "tool", "boiler");
recipe("gunpowder", "tool", "bullet");
recipe("bullet", "firearm", "shell");
recipe("sun", "clock", "sundial");
recipe("thread", "tool", "fabric");
recipe("house", "tool", "factory");
recipe("sun", "rain", "rainbow");
recipe("rainbow", "rainbow", "double rainbow");
recipe("rainbow", "water", "paint");
recipe("paint", "human", "painter");
recipe("rainbow", "sheep", "jeb_");
recipe("pencil", "tool", "mechanical pencil");
recipe("pencil", "paint", "marker");
recipe("paint", "wall", "mural");
recipe("tool", "soil", "field");
recipe("tool", "lightbulb", "flashlight");
recipe("tool", "animal", "human");
recipe("tool", "wheel", "machine");
recipe("tool", "tool", "machine");
recipe("tool", "container", "toolbox");
recipe("boiler", "tool", "container");
recipe("tool", "chicken", "meat");
recipe("life", "stone", "egg");
recipe("egg", "chicken", "paradox");
recipe("tool", "ore", "metal");
recipe("metal", "oxygen", "rust");
recipe("rust", "electrolysis", "iron");
recipe("bird", "meat", "poultry");
recipe("meat", "cow", "beef");
recipe("meat", "pig", "pork");
recipe("metal", "thread", "needle");
recipe("fire", "egg", "omelette");
recipe("water", "double rainbow", "paint");
recipe("syringe", "idea", "vaccine");
recipe("storm", "tool", "umbrella");
recipe("animal", "tobacco", "tobacco hornworm");
recipe("tobacco hornworm", "time", "carolina sphinx moth");
recipe("time", "life", "death");
recipe("animal", "milk", "cat");
recipe("cat", "plant", "catnip");
recipe("cat", "flower", "catnip");
recipe("container", "livestock", "barn");
recipe("container", "bird", "birdcage");
recipe("birdcage", "zoo", "aviary");
recipe("birdcage", "ocean", "crab trap");
recipe("birdcage", "sea", "crab trap");
recipe("crab trap", "animal", "crab");
recipe("crab", "tool", "claw");
recipe("crab", "palm", "coconut crab");
recipe("paper", "paper", "paperboard");
recipe("paperboard", "paperboard", "cardboard");
recipe("cardboard", "cardboard", "box");
recipe("cat", "box", "schrödinger's cat");
recipe("schrödinger's cat", "philosophy", "quantum superposition");
recipe("human", "schrödinger's cat", "quantum collapse");
recipe("quantum collapse", "quantum superposition", "choice");
recipe("love", "flower", "rose");
recipe("planet", "acid rain", "venus");
recipe("acid rain", "human", "corpse");
recipe("smoke", "rain", "acid rain");
recipe("planet", "ocean", "neptune");
recipe("planet", "sun", "mercury (planet)");
recipe("ring", "planet", "saturn");
recipe("telescope", "space", "celestial body");
recipe("celestial body", "sun", "star");
recipe("celestial body", "earth", "planet");
recipe("celestial body", "earth (planet)", "planet");
recipe("celestial body", "venus", "planet");
recipe("celestial body", "mercury", "planet");
recipe("celestial body", "neptune", "planet");
recipe("celestial body", "saturn", "planet");
recipe("celestial body", "crab", "cancer");
recipe("crab", "constellation", "cancer");
recipe("cancer", "human", "corpse");
recipe("cancer", "science", "disease");
recipe("cancer", "animal", "crab");
recipe("diamond", "container", "safe");
recipe("sun", "flower", "sunflower");
recipe("bird", "antarctica", "penguin");
recipe("tree", "beach", "palm");
recipe("tree", "island", "palm");
recipe("star", "star", "asterism");
recipe("asterism", "asterism", "constellation");
recipe("human", "cold", "illness");
recipe("paint", "science", "colorology");
recipe("colorology", "philosophy", "color");
recipe("color", "coal", "black");
recipe("color", "obsidian", "black");
recipe("color", "grass", "green");
recipe("color", "sky", "blue");
recipe("color", "ocean", "blue");
recipe("color", "zombie", "green");
recipe("color", "cancer", "purple");
recipe("color", "sand", "yellow");
recipe("color", "sun", "yellow");
recipe("color", "neptune", "blue");
recipe("color", "rose", "red");
recipe("color", "ice", "blue");
recipe("color", "mud", "brown");
recipe("earth", "fire", "lava");
recipe("color", "lava", "red");
recipe("color", "wood", "brown");
recipe("human", "choice", "conscience");
recipe("metal", "electricity", "copper");
recipe("color", "copper", "orange");
recipe("orange", "cat", "tabby");
recipe("copper", "lightning", "lightning rod");
recipe("lightning rod", "lightning", "electricity");
recipe("obsidian", "philosophy", "sharp");
recipe("sharp", "metal", "blade");
recipe("blade", "human", "blood");
recipe("color", "blood", "red");
recipe("blood", "needle", "syringe");
recipe("blade", "wood", "axe");
recipe("paper", "blade", "confetti");
recipe("bone", "blade", "claw");
recipe("axe", "blade", "pickaxe");
recipe("pickaxe", "cave", "mineral");
recipe("blade", "cow", "leather");
recipe("blade", "pencil", "pencil sharpener");
recipe("blade", "meat", "knife");
recipe("blade", "grass", "scythe");
recipe("scythe", "death", "grim reaper");
recipe("grim reaper", "human", "death");
recipe("star", "blade", "shuriken");
recipe("blade", "metal", "sword");
recipe("blade", "blade", "scissors");
recipe("scissors", "idea", "cut");
recipe("cut", "sword", "slash");
recipe("sword", "fish", "swordfish");
recipe("bird", "fish", "flying fish");
recipe("color", "light", "vibrant");
recipe("light", "black", "shade");
recipe("shade", "color", "muted");
recipe("venus", "human", "female");
recipe("dust", "planet", "mars");
recipe("mars", "human", "male");
recipe("mars", "volcano", "olympus mons");
recipe("mars", "celestial body", "planet");
recipe("choice", "love", "partner");
recipe("male", "female", "love");
recipe("male", "earth", "adam");
recipe("female", "earth", "eve");
recipe("adam", "garden", "garden of eden");
recipe("garden of eden", "tree", "tree of the knowledge of good and evil");
recipe("color", "cloud", "white");
recipe("ice", "rain", "hail");
recipe("cold", "rain", "snow");
recipe("snow", "human", "snowman");
recipe("snowman", "female", "snowwoman");
recipe("snowwoman", "male", "snowman");
recipe("male", "cow", "bull");
recipe("female", "rose", "carnation");
recipe("tree", "sun", "fruit");
recipe("fruit", "time", "mold");
recipe("mold", "science", "penicillin");
recipe("mold", "wood", "rot");
recipe("flower", "pond", "lily pad");
recipe("lily pad", "animal", "frog");
recipe("fish", "egg", "roe");
recipe("frog", "egg", "frogspawn");
recipe("frogspawn", "time", "tadpole");
recipe("fruit", "meat", "food");
recipe("food", "roe", "caviar");
recipe("science", "air", "gas");
recipe("science", "water", "liquid");
recipe("science", "rock", "solid");
recipe("gas", "planet", "gas giant");
recipe("solid", "planet", "rocky planet");
recipe("liquid", "planet", "hycean planet");
recipe("ice", "planet", "ice giant");
recipe("gas giant", "ice", "ice giant");
recipe("cheese", "sky", "moon");
recipe("moon", "sky", "night");
recipe("day", "moon", "night");
recipe("night", "sun", "day");
recipe("sky", "stone", "moon");
recipe("story", "human", "history");
recipe("story", "country", "history");
recipe("life", "book", "biography");
recipe("book", "human", "author");
recipe("author", "biography", "biographer");
recipe("scientist", "human", "anthropologist");
recipe("anthropologist", "science", "anthropology");
recipe("shuriken", "human", "ninja");
recipe("star", "fish", "starfish");
recipe("monarch", "country", "empire");
recipe("empire", "red", "ussr");
recipe("ussr", "time", "collapse");
recipe("ussr", "ideology", "communism");
recipe("collapse", "boulder", "wreaking ball");
recipe("continent", "australia", "oceania");
recipe("continent", "canada", "north america");
recipe("continent", "jamaica", "north america");
recipe("continent", "cuba", "north america");
recipe("copper", "thread", "wire");
recipe("wire", "copper", "copper wire");
recipe("copper wire", "copper wire", "coil");
recipe("coil", "electricity", "magnet");
recipe("hammer", "tool", "nail");
recipe("nail", "tool", "hammer");
recipe("food", "human", "chef");
recipe("chef", "livestock", "butcher");
recipe("color", "cheese", "yellow");
recipe("machine", "bird", "plane");
recipe("plane", "paper", "paper airplane");
recipe("wheel", "machine", "bicycle");
recipe("pressure", "fossil", "oil");
recipe("bicycle", "machine", "motorcycle");
recipe("motorcycle", "machine", "car");
recipe("car", "oil", "motor oil");
recipe("oil", "country", "saudi arabia");
recipe("saudi arabia", "human", "saudi arabian");
recipe("graveyard", "story", "ghost");
recipe("graveyard", "night", "ghost");
recipe("story", "time", "legend");
recipe("legend", "graveyard", "ghost");
recipe("ghost", "science", "ghostology");
recipe("ghost", "village", "ghosttown");
recipe("ghost", "town", "ghosttown");
recipe("ghost", "human", "possession");
recipe("ghost", "ghost", "spirit");
recipe("ghost", "philosophy", "spirit");
recipe("spirit", "human", "soul");
recipe("ghost", "fabric", "sheet");
recipe("ghost", "fruit", "ghost pepper");
recipe("hearth", "human", "warmth");
recipe("warmth", "science", "heat");
recipe("heat", "fruit", "pepper");
recipe("paint", "black", "ink");
recipe("ink", "fish", "squid");
recipe("squid", "food", "calamari");
recipe("life", "fruit", "lemon");
recipe("orange", "fruit", "orange");
recipe("country", "fabric", "flag");
recipe("flag", "science", "vexillology");
recipe("ghostology", "human", "ghostologist");
recipe("vexillology", "human", "vexillologist");
recipe("communism", "human", "communist");
recipe("communist", "ussr", "joseph stalin");
recipe("joseph stalin", "ideology", "stalinism");
recipe("stalinism", "human", "stalinist");
recipe("atmosphere", "machine", "rocket");
recipe("rocket", "space", "spaceship");
recipe("telescope", "human", "astronomer");
recipe("astronomer", "science", "astronomy");
recipe("space", "science", "astronomy");
recipe("soil", "animal", "worm");
recipe("worm", "idea", "geophagia");
recipe("worm", "fruit", "apple");
recipe("apple", "idea", "gravity");
recipe("ocean", "moon", "tide");
recipe("night", "moon", "afternoon");
recipe("morning", "afternoon", "noon");
recipe("noon", "time", "12:00");
recipe("12:00", "night", "midnight");
recipe("midnight", "ocean", "midnight ocean");
recipe("sun", "light", "sunlight");
recipe("gravity", "pressure", "blackhole");
recipe("oxygen", "human", "carbon dioxide");
recipe("carbon dioxide", "plant", "oxygen");
recipe("time", "history", "past");
recipe("past", "human", "monkey");
recipe("monkey", "fruit", "banana");
recipe("glass", "sea", "sea glass");
recipe("light", "house", "window");
recipe("mexico", "food", "taco");
recipe("past", "ussr", "russian empire");
recipe("russian empire", "past", "tsardom of russia");
recipe("fruit", "water", "juice");
recipe("juice", "time", "alcohol");
recipe("juice", "cold", "popsicle");
recipe("juice", "ice", "popsicle");
recipe("juice", "carbon dioxide", "soda");
recipe("soda", "science", "carbonation");
recipe("carbonation", "juice", "soda");
recipe("water", "heat", "boil");
recipe("boil", "juice", "sugar");
recipe("boil", "water", "steam");
recipe("boil", "sugar", "caramel");
recipe("human", "alcohol", "drunk");
recipe("alcohol", "carbonation", "champagne");
recipe("alcohol", "carbon dioxide", "champagne");
recipe("alcohol", "rose", "perfume");
recipe("alcohol", "flower", "perfume");
recipe("fruit", "alcohol", "wine");
recipe("liquid", "container", "bottle");
recipe("alcohol", "container", "bottle");
recipe("dust", "color", "chalk");
recipe("dust", "white", "chalk");
recipe("stick", "plant", "leaf");
recipe("time", "sun", "summer");
recipe("summer", "snow", "winter");
recipe("summer", "flower", "spring");
recipe("spring", "leaf", "autumn");
recipe("mountain", "rain", "river");
recipe("river", "philosophy", "motion");
recipe("motion", "gravity", "projectile motion");
recipe("motion", "air", "wind");
recipe("motion", "atmosphere", "wind");
recipe("wind", "dust", "dust devil");
recipe("wind", "wind", "tornado");
recipe("tornado", "dust", "dust devil");
recipe("tornado", "water", "cyclone");
recipe("tornado", "ocean", "hurricane");
recipe("wind", "snow", "blizzard");
recipe("sand", "wind", "sandstorm");
recipe("sandstorm", "snow", "blizzard");
recipe("blizzard", "sand", "sandstorm");
recipe("beach", "wind", "dune");
recipe("leaf", "wind", "abscission");
recipe("wind", "plant", "dandelion");
recipe("planet", "hurricane", "neptune");
recipe("wood", "wind", "flute");
recipe("paper", "wind", "kite");
recipe("tree", "wind", "abscission");
recipe("boat", "wind", "sailboat");
recipe("stone", "wind", "sand");
recipe("sea", "wind", "wave");
recipe("ocean", "wind", "wave");
recipe("wave", "air", "sound");
recipe("air", "space", "vacuum");
recipe("house", "wind", "windmill");
recipe("windmill", "metal", "wind turbine");
recipe("flower", "wind", "pollen");
recipe("pollen", "human", "allergy");
recipe("desert", "wind", "sandstorm");
recipe("wind", "electricity", "wind turbine");
recipe("wind turbine", "wind", "electricity");
recipe("windmill", "country", "netherlands");
recipe("netherlands", "continent", "europe");
recipe("netherlands", "human", "dutch");
recipe("plane", "blade", "helicopter");
recipe("windmill", "electricity", "wind turbine");
recipe("sunflower", "windmill", "oil");
recipe("farmer", "plant", "wheat");
recipe("wheat", "windmill", "flour");
recipe("wheat", "alcohol", "beer");
recipe("beer", "human", "drunk");
recipe("wine", "human", "drunk");
recipe("wheat", "milk", "cereal");
recipe("wheat", "stone", "flour");
recipe("blade", "wheat", "scythe");
recipe("wheat", "house", "silo");
recipe("wheat", "container", "silo");
recipe("wheat", "barn", "silo");
recipe("machine", "windmill", "wind turbine");
recipe("sea", "plane", "seaplane");
recipe("ocean", "plane", "seaplane");
recipe("crab", "science", "carcinization");
recipe("meat", "vulture", "bone");
recipe("food", "vulture", "bone");
recipe("bone", "chicken", "chicken wing");
recipe("bone", "flute", "gudi");
recipe("flute", "human", "flutist");
recipe("gudi", "human", "gudi player");
recipe("flute", "wind", "music");
recipe("gudi", "wind", "music");
recipe("bone", "bone", "skeleton");
recipe("bone", "sea", "coral");
recipe("bone", "ocean", "coral");
recipe("bone", "time", "fossil");
recipe("bone", "earth", "fossil");
recipe("bone", "rock", "fossil");
recipe("bone", "rock", "fossil");
recipe("color", "snow", "white");
recipe("color", "bone", "white");
recipe("color", "blade", "grey");
recipe("steam engine", "boat", "steamboat");
recipe("human", "electricity", "electrician");
recipe("human", "lightning", "corpse");
recipe("apple", "gravity", "fall");
recipe("gravity", "philosophy", "fall");
recipe("fall", "spring", "autumn");
recipe("fall", "water", "waterfall");
recipe("water", "gravity", "waterfall");
recipe("river", "gravity", "waterfall");
recipe("moon", "gravity", "orbit");
recipe("orbit", "machine", "satellite");
recipe("orbit", "planet", "moon");
recipe("machine", "moon", "satellite");
recipe("satellite", "philosophy", "orbit");
recipe("life", "space", "alien");
recipe("idea", "fire", "hot");
recipe("cold", "fire", "hot");
recipe("cold", "hot", "warm");
recipe("warm", "warm", "lukewarm");
recipe("warm", "water", "lukewarm");
recipe("hot", "planet", "mercury (planet)");
recipe("mercury", "celestial body", "mercury (planet)");
recipe("mercury (planet)", "celestial body", "planet");
recipe("mercury (planet)", "life", "alien");
recipe("venus", "life", "alien");
recipe("earth (planet)", "life", "human");
recipe("mars", "life", "alien");
recipe("saturn", "life", "alien");
recipe("jupiter", "life", "alien");
recipe("planet", "storm", "jupiter");
recipe("gas", "human", "fart");
recipe("fart", "planet", "uranus");
recipe("uranus", "life", "alien");
recipe("neptune", "life", "alien");
recipe("alien", "mercury (planet)", "mercurian");
recipe("alien", "venus", "venusian");
recipe("alien", "plane", "ufo");
recipe("alien", "helicopter", "ufo");
recipe("alien", "earth (planet)", "terran");
recipe("alien", "mars", "martian");
recipe("alien", "saturn", "saturnian");
recipe("alien", "jupiter", "jovian");
recipe("alien", "uranus", "uranian");
recipe("alien", "neptune", "neptunian");
recipe("light", "firearm", "laser");
recipe("beer", "country", "germany");
recipe("germany", "human", "german");
recipe("germany", "continent", "europe");
recipe("russia", "continent", "eurasia");
recipe("science", "drunk", "intoxication");
recipe("thread", "plant", "vine");
recipe("vine", "fruit", "grapes");
recipe("grapes", "purple", "red grapes");
recipe("grapes", "green", "white grapes");
recipe("music", "paper", "sheet music");
recipe("music", "wood", "drum");
recipe("machine", "life", "robot");
recipe("robot", "idea", "ai");
recipe("music", "stone", "rock music");
recipe("music", "rock", "rock music");
recipe("music", "book", "sheet music");
recipe("park", "tree", "forest");
recipe("tree", "tree", "forest");
recipe("forest", "rain", "rainforest");
recipe("rainforest", "country", "brazil");
recipe("brazil", "music", "phonk");
recipe("brazil", "phonk", "brazilian phonk");
recipe("brazil", "human", "brazilian");
recipe("sheet", "window", "curtain");
recipe("fabric", "window", "curtain");
recipe("forest", "animal", "wild animal");
recipe("forest", "life", "wild animal");
recipe("eternal", "life", "immortality");
recipe("immortality", "human", "immortal");
recipe("immortal", "legend", "deity");
recipe("deity", "human", "demigod");
recipe("demigod", "female", "demigoddess");
recipe("demigoddess", "male", "demigod");
recipe("demigod", "demigod", "god");
recipe("god", "female", "goddess");
recipe("goddess", "male", "god");
recipe("immortal", "fruit", "peach");
recipe("god", "lightning", "zeus");
recipe("god", "storm", "zeus");
recipe("lightning", "sound", "thunder");
recipe("cheese", "time", "mold");
recipe("zeus", "country", "greece");
recipe("greece", "continent", "europe");
recipe("greece", "human", "greek");
recipe("country", "sun", "japan");
recipe("brazil", "continent", "south america");
recipe("japan", "human", "japanese");
recipe("japan", "continent", "asia");
recipe("asia", "europe", "eurasia");
recipe("ussr", "continent", "eurasia");
recipe("japan", "fish", "koi");
recipe("tree", "japan", "cherry blossom");
recipe("fruit", "japan", "apple");
recipe("japan", "cat", "neko");
recipe("death", "japan", "suicide");
recipe("suicide", "human", "corpse");
recipe("asia", "wheat", "rice");
recipe("animal", "wire", "snake");
recipe("animal", "vine", "snake");
recipe("snake", "tree of the knowledge of good and evil", "temptation");
recipe("temptation", "alcohol", "addiction");
recipe("temptation", "weed", "addiction");
recipe("temptation", "cigarette", "smoking");
recipe("temptation", "smoking", "addiction");
recipe("eve", "temptation", "disobedience");
recipe("demigod", "human", "demihuman");
recipe("demihuman", "animal", "therian");
recipe("therian", "cat", "cat therian");
recipe("cat therian", "female", "catgirl");
recipe("blood", "fish", "shark");
recipe("shark", "hammer", "hammerhead");
recipe("shark", "lemon", "lemon shark");
recipe("rock", "obsidian", "blade");
recipe("pressure", "earth", "earthquake");
recipe("earthquake", "volcano", "eruption");
recipe("earthquake", "mars", "marsquake");
recipe("earthquake", "sun", "sunquake");
recipe("cancer", "sun", "umbra");
recipe("rock", "water", "coral");
recipe("sea", "dust", "sand");
recipe("sand", "castle", "sandcastle");
recipe("dust", "earth", "dirt");
recipe("pollen", "animal", "bee");
recipe("bee", "house", "beehive");
recipe("bee", "container", "beehive");
recipe("bee", "food", "honey");
recipe("liquid", "food", "drink");
recipe("drink", "fruit", "juice");
recipe("dirt", "earth", "mound");
recipe("hourglass", "energy", "time");
recipe("hourglass", "gravity", "time");
recipe("hourglass", "fall", "time");
recipe("fire", "beach", "bonfire");
recipe("campfire", "beach", "bonfire");
recipe("gunpowder", "dirt", "landmine");
recipe("explosion", "dirt", "landmine");
recipe("landmine", "human", "corpse");
recipe("landmine", "philosophy", "bomb");
recipe("bomb", "earth", "landmine");
recipe("bomb", "dirt", "landmine");
recipe("desert", "desert", "sahara");
recipe("sahara", "ice", "antarctica");
recipe("snow", "desert", "antarctica");
recipe("snow", "sahara", "antarctica");
recipe("country", "country","diplomacy");
recipe("obsidian", "glass", "obsidian glass");
recipe("glass", "pressure", "tempered glass");
recipe("dust", "mountain", "snow");
recipe("fire", "mountain", "volcano");
recipe("lava", "mountain", "volcano");
recipe("lava", "pond", "lava lake");
recipe("lava", "lake", "lava lake");
recipe("energy", "pressure", "heat");
recipe("fire", "energy", "thermal energy");
recipe("fire", "thermal energy", "heat");
recipe("glass", "color", "opaque");
recipe("glass", "energy", "reflection");
recipe("reflection", "glass", "mirror");
recipe("reflection", "water", "mirror");
recipe("puddle", "wave", "ripple");
recipe("water", "steam", "evaporation");
recipe("mud", "fire", "brick");
recipe("cloud", "air", "sky");
recipe("water", "desert", "oasis");
recipe("oasis", "heat", "illusion");
recipe("plant", "desert", "cactus");
recipe("universe", "explosion", "the big bang");
recipe("cactus", "flower", "cactus bloom");
recipe("universe", "fire", "hell");
recipe("hell", "god", "hades");
recipe("hades", "country", "greece");
recipe("mars", "mountain", "olympus mons");
recipe("storm", "energy", "electricity");
recipe("universe", "universe", "multiverse");
recipe("multiverse", "multiverse", "megaverse");
recipe("megaverse", "megaverse", "gigaverse");
recipe("gigaverse", "gigaverse", "teraverse");
recipe("teraverse", "teraverse", "petaverse");
recipe("petaverse", "petaverse", "exaverse");
recipe("exaverse", "exaverse", "zettaverse");
recipe("zettaverse", "zettaverse", "yottaverse");
recipe("yottaverse", "yottaverse", "ronnaverse");
recipe("ronnaverse", "ronnaverse", "quettaverse");
recipe("quettaverse", "quettaverse", "omniverse");
recipe("omniverse", "omniverse", "the barrel");
recipe("the barrel", "the barrel", "beyond");
recipe("beyond", "beyond", "transcendentem");
recipe("transcendentem", "transcendentem", "transcendentem continuum");
recipe("rain", "storm", "rainstorm");
recipe("rainstorm", "tornado", "typhoon");
recipe("rainstorm", "wind", "typhoon");
recipe("earth", "mars", "colonization");
recipe("earth (planet)", "mars", "colonization");
recipe("star", "earth", "sun");
recipe("star", "earth (planet)", "sun");
recipe("bird", "fire", "phoenix");
recipe("phoenix", "death", "rebirth");
recipe("bird", "thunder", "thunderbird");
recipe("water", "alcohol", "vodka");
recipe("vodka", "country", "russia");
recipe("russia", "human", "russian");
recipe("russian", "astronaut", "cosmonaut");
recipe("russia", "stalinism", "ussr");
recipe("russia", "communism", "ussr");
recipe("russia", "animal", "bear");
recipe("bear", "asia", "panda");
recipe("panda", "country", "china");
recipe("china", "continent", "asia");
recipe("china", "human", "chinese");
recipe("china", "communism", "people's republic of china");
recipe("people's republic of china", "ideology", "communism");
recipe("communist", "people's republic of china", "mao zedong");
recipe("mao zedong", "ideology", "maoism");
recipe("panda", "food", "bamboo");
recipe("plant", "china", "bamboo");
recipe("bamboo", "boat", "raft");
recipe("wood", "boat", "raft");
recipe("forest", "city", "park");
recipe("forest", "town", "park");
recipe("street", "forest", "path");
recipe("street", "park", "path");
recipe("path", "car", "road");
recipe("street", "path", "road");
recipe("light", "road", "traffic light");
recipe("light", "street", "traffic light");
recipe("animal", "china", "panda");
recipe("black", "white", "grey");
recipe("grey", "white", "monochrome");
recipe("grey", "black", "monochrome");
recipe("monochrome", "color", "polychrome");
recipe("china", "island", "taiwan");
recipe("taiwan", "human", "taiwanese");
recipe("taiwan", "continent", "asia");
recipe("village", "human", "villager");
recipe("monarch", "male", "king");
recipe("monarch", "female", "queen");
recipe("cat", "cat", "clowder");
recipe("metal", "yellow", "gold");
recipe("metal", "sand", "silicon");
recipe("gold", "king", "crown");
recipe("crown", "idea", "hat");
recipe("hat", "king", "crown");
recipe("hat", "queen", "crown");
recipe("gold", "queen", "crown");
recipe("hat", "chef", "toque");
recipe("paper", "gold", "money");
recipe("money", "safe", "bank");
recipe("money", "house", "bank");
recipe("money", "idea", "currency");
recipe("container", "gold", "safe");
recipe("gold", "philosophy", "alchemist");
recipe("alchemist", "science", "alchemy");
recipe("alchemy", "metal", "gold");
recipe("alchemy", "iron", "gold");
recipe("money", "pig", "piggy bank");
recipe("gold", "pig", "piggy bank");
recipe("love", "gold", "ring");
recipe("rose", "gold", "rose gold");
recipe("rose gold", "color", "pink");
recipe("sun", "moon", "eclipse");
recipe("eclipse", "sun", "solar eclipse");
recipe("eclipse", "moon", "lunar eclipse");
recipe("banana", "human", "slip");
recipe("slip", "human", "fall");
recipe("fart", "container", "butt");
recipe("butt", "wood", "chair");
recipe("chair", "wood", "table");
recipe("table", "glass", "glass table");
recipe("table", "table", "desk");
recipe("quantum superposition", "science", "quantum physics");
recipe("quantum physics", "light", "lightwave");
recipe("lightwave", "colorology", "wavelength");
recipe("light", "wave", "lightwave");
recipe("female", "female", "yuri");
recipe("male", "male", "yaoi");
recipe("yaoi", "human", "gay");
recipe("yuri", "human", "lesbian");
recipe("gay", "female", "lesbian");
recipe("oxygen", "table", "periodic table");
recipe("periodic table", "idea", "element");
recipe("periodic table", "philosophy", "element");
recipe("element", "time", "cesium");
recipe("cesium", "clock", "atomic clock");
recipe("atomic clock", "time", "second");
recipe("clock", "bird", "cuckoo");
recipe("cuckoo", "clock", "cuckoo clock");
recipe("dinosaur", "time", "old");
recipe("castle", "collapse", "ruins");
recipe("ruins", "time", "old");
recipe("ruins", "idea", "old");
recipe("old", "clock", "grandfather clock");
recipe("second", "second", "minute");
recipe("minute", "minute", "hour");
recipe("hour", "hour", "day");
recipe("day", "day", "week");
recipe("week", "week", "fortnight");
recipe("fortnight", "fortnight", "month");
recipe("month", "month", "year");
recipe("year", "year", "decade");
recipe("decade", "decade", "century");
recipe("century", "century", "millennium");
recipe("millennium", "millennium", "megayear");
recipe("megayear", "megayear", "eon");
recipe("eon", "eon", "timeless");
recipe("maoism", "human", "maoist");
recipe("moon", "moon", "moonmoon");
recipe("moon", "satellite", "moonmoon");
recipe("snake", "human", "gorgon");
recipe("gorgon", "king", "medusa");
recipe("medusa", "sword", "gorgon head");
recipe("past", "greece", "ancient greece");
recipe("old", "greece", "ancient greece");
recipe("eternal", "tree", "evergreen");
recipe("lemon", "pressure", "lemonade");
recipe("lemon", "water", "lemonade");
recipe("lemon", "juice", "lemon juice");
recipe("lemon", "green", "lime");
recipe("lemon", "table", "lemonade stand");
recipe("lemon", "box", "lemonade stand");
recipe("lemonade stand", "human", "vendor");
recipe("lemonade stand", "money", "economy");
recipe("lemonade stand", "vendor", "child");
recipe("child", "male", "boy");
recipe("child", "female", "girl");
recipe("girl", "human", "mother");
recipe("boy", "human", "father");
recipe("girl", "time", "woman");
recipe("boy", "time", "man");
recipe("man", "philosophy", "masculine");
recipe("woman", "philosophy", "feminine");
recipe("feminine", "boy", "femboy");
recipe("masculine", "girl", "tomboy");
recipe("pool", "river", "lazy river");
recipe("lazy river", "park", "waterpark");
recipe("pool", "park", "waterpark");
recipe("waterpark", "river", "lazy river");
recipe("waterpark", "ocean", "wave pool");
recipe("waterpark", "wave", "wave pool");
recipe("waterpark", "house", "hotel");
recipe("house", "park", "apartment");
recipe("apartment", "apartment", "hotel");
recipe("hotel", "road", "motel");
recipe("hotel", "street", "motel");
recipe("liquid", "metal", "mercury");
recipe("mercury", "table", "periodic table");
recipe("element", "mercury (planet)", "mercury");
recipe("clock", "water", "clepsydra");
recipe("clock", "earth (planet)", "doomsday clock");
recipe("ideology", "human", "ideologist");
recipe("space", "time", "spacetime");
recipe("ideologist", "science", "ideology");
recipe("male", "idea", "gender");
recipe("female", "idea", "gender");
recipe("female", "day", "march 8th");
recipe("male", "day", "november 19th");
recipe("human", "day", "birthday");
recipe("earth (planet)", "day", "april 22nd");
recipe("battery", "sun", "solar panel");
recipe("solar panel", "farm", "solar farm");
recipe("solar panel", "sun", "electricity");
recipe("solar panel", "light", "electricity");
recipe("blackhole", "human", "spaghettification");
recipe("food", "spaghettification", "spaghetti");
recipe("spaghetti", "country", "italy");
recipe("italy", "continent", "europe");
recipe("italy", "human", "italian");
recipe("time", "universe", "big freeze");
recipe("economy", "ideology", "capitalism");
recipe("capitalism", "country", "united states of america");
recipe("united states of america", "continent", "north america");
recipe("united states of america", "human", "american");
recipe("vacuum", "sky", "space");
recipe("moon", "wild animal", "wolf");
recipe("wolf", "human", "werewolf");
recipe("wolf", "house", "dog");
recipe("dog", "idea", "domestication");
recipe("domestication", "wolf", "dog");
recipe("domestication", "animal", "pet");
recipe("space", "mirror", "telescope");
recipe("sun", "element", "hydrogen");
recipe("hydrogen", "table", "periodic table");
recipe("hell", "obsidian", "nether");
recipe("nether", "ore", "netherite");
recipe("nether", "ocean", "lava ocean");
recipe("sugar", "father", "sugar daddy");
recipe("blackhole", "white", "whitehole");
recipe("whitehole", "blackhole", "tug-of-war");
recipe("blackhole", "light", "nothing");
recipe("snow", "heat", "droplet");
recipe("droplet", "plant", "dew");
recipe("dew", "honey", "honeydew");
recipe("medusa", "snake", "hair");
recipe("gorgon", "snake", "hair");
recipe("medusa", "hair", "snake");
recipe("gorgon", "hair", "snake");
recipe("hair", "human", "barber");
recipe("barber", "hair", "cut");
recipe("cut", "hair", "bald");
recipe("bald", "cancer", "chemotherapy");
recipe("bald", "science", "alopecia");
recipe("barber", "science", "trichology");
recipe("trichology", "human", "trichologist");
recipe("capitalism", "human", "capitalist");
recipe("tempered glass", "space", "space suit");
recipe("barber", "day", "september 16th");
recipe("trichologist", "day", "september 16th");
recipe("feminine", "ideology", "feminism");
recipe("feminism", "human", "feminist");
recipe("human", "hell", "demon");
recipe("demon", "love", "evil");
recipe("evil", "love", "lust");
recipe("lust", "demon", "succubus");
recipe("succubus", "male", "incubus");
recipe("incubus", "female", "succubus");
recipe("succubus", "male", "sex");
recipe("incubus", "female", "sex");
recipe("sex", "ideology", "sexocracy");
recipe("sexocracy", "human", "sexocrat");
recipe("sex", "female", "pregnant");
recipe("addiction", "alcohol", "alcoholism");
recipe("alcoholism", "human", "alcoholic");
recipe("machine", "desk", "computer");
recipe("computer", "landmine", "minesweeper");
recipe("minesweeper", "idea", "game");
