recipe("water", "water", "puddle");
recipe("water", "fire", "steam");
recipe("water", "air", "mist");
recipe("water", "earth", "mud");
recipe("puddle", "puddle", "pool");
recipe("mud", "earth", "clay");
recipe("clay", "fire", "brick");
recipe("earth", "life", "soil");
recipe("earth", "earth", "rock");
recipe("rock", "fire", "lava");
recipe("pool", "pool", "pond");
recipe("pond", "pond", "lake");
recipe("lake", "lake", "bay");
recipe("bay", "bay", "sea");
recipe("sea", "sea", "ocean");
recipe("air", "mist", "cloud");
recipe("rock", "rock", "boulder");
recipe("boulder", "boulder", "hill");
recipe("hill", "hill", "mountain");
recipe("mountain", "lava", "volcano");
recipe("mountain", "mountain", "mountain range");
recipe("mountain range", "mountain range", "continent");
recipe("continent", "ocean", "planet");
recipe("brick", "brick", "wall");
recipe("wall", "wall", "house");
recipe("house", "house", "street");
recipe("street", "street", "neighborhood");
recipe("neighborhood", "neighborhood", "village");
recipe("village", "village", "town");
recipe("town", "town", "city");
recipe("city", "city", "metropolis");
recipe("metropolis", "metropolis", "megacity");
recipe("megacity", "megacity", "conurbation");
recipe("conurbation", "conurbation", "megaregion");
recipe("megaregion", "megaregion", "eperopolis");
recipe("eperopolis", "eperopolis", "ecumenopolis");
recipe("cloud", "water", "rain");
recipe("air", "air", "pressure");
recipe("lava", "water", "obsidian");
recipe("volcano", "water", "geyser");
recipe("volcano", "ocean", "island");
recipe("island", "island", "archipelago");
recipe("continent", "continent", "supercontinent");
recipe("planet", "planet", "solar system");
recipe("house", "fire", "hearth");
recipe("village", "wall", "fort");
recipe("fort", "house", "fortress");
recipe("fortress", "fortress", "castle");
recipe("castle", "castle", "palace");
recipe("hill", "water", "valley");
recipe("mountain", "lake", "alpine lake");
recipe("mountain range", "sea", "fjord");
recipe("mist", "mist", "fog");
recipe("fog", "fog", "cloud");
recipe("steam", "fire", "smoke");
recipe("soil", "house", "garden");
recipe("air", "earth", "dust");
recipe("dust", "rain", "acid rain");
recipe("dust", "fire", "gunpowder");
recipe("gunpowder", "pressure", "deflagration");
recipe("air", "planet", "atmosphere");
recipe("atmosphere", "mist", "cloud");
recipe("water", "planet", "hydrosphere");
recipe("fire", "gunpowder", "explosion");
recipe("explosion", "pressure", "overpressure");
recipe("steam engine", "explosion", "combustion engine");
recipe("earth", "cloud", "fog");
recipe("wall", "water", "dam");
recipe("fire", "fire", "energy");
recipe("energy", "steam", "steam engine");
recipe("energy", "gunpowder", "explosion");
recipe("energy", "air", "thermal energy");
recipe("ocean", "ocean", "pressure");
recipe("plant", "earth", "grass");
recipe("plant", "lake", "swamp");
recipe("plant", "pond", "reed");
recipe("hydrosphere", "energy", "primordial soup");
recipe("primordial soup", "energy", "life");
recipe("life", "water", "plankton");
recipe("life", "air", "aeroplankton");
recipe("life", "soil", "plant");
recipe("plant", "swamp", "cattail");
recipe("plant", "sea", "seaweed");
recipe("air", "lava", "stone");
recipe("stone", "air", "sand");
recipe("sand", "ocean", "beach");
recipe("sand", "fire", "glass");
recipe("mud", "sand", "clay");
recipe("clay", "life", "human");
recipe("human", "castle", "monarch");
recipe("fjord", "earth", "land");
recipe("monarch", "land", "country");
recipe("fire", "planet", "star");
recipe("country", "lake", "canada");
recipe("human", "canada", "canadian");
recipe("land", "land", "continent");
recipe("house", "glass", "greenhouse");
recipe("human", "house", "family");
recipe("life", "land", "animal");
recipe("animal", "air", "bird");
recipe("animal", "ocean", "fish");
recipe("animal", "lake", "fish");
recipe("animal", "sea", "fish");
recipe("fish", "glass", "aquarium");
recipe("aquarium", "land", "zoo");
recipe("zoo", "water", "aquarium");
recipe("zoo", "air", "aviary");
recipe("aviary", "land", "zoo");
recipe("brick", "fire", "kiln");
recipe("kiln", "kiln", "furnace");
recipe("kiln", "clay", "ceramic");
recipe("rain", "energy", "lightning");
recipe("lightning", "cloud", "storm cloud");
recipe("steam engine", "steam", "electricity");
recipe("electricity", "cloud", "thundercloud");
recipe("storm", "electricity", "thunderstorm");
recipe("sand", "glass", "hourglass");
recipe("solar system", "solar system", "galaxy");
recipe("galaxy", "galaxy", "galaxy group");
recipe("galaxy group", "galaxy group", "galaxy cluster");
recipe("galaxy cluster", "galaxy cluster", "galaxy supercluster");
recipe("galaxy supercluster", "galaxy supercluster", "galaxy filament");
recipe("galaxy filament", "galaxy filament", "universe");
recipe("universe", "universe", "multiverse");
recipe("universe", "human", "science");
recipe("science", "science", "technology");
recipe("science", "human", "scientist");
recipe("science", "technology", "technoscience");
recipe("electricity", "glass", "lightbulb");
recipe("lightbulb", "human", "idea");
recipe("idea", "human", "philosophy");
recipe("philosophy", "country", "ideology");
recipe("philosophy", "house", "container");
recipe("container", "electricity", "battery");
recipe("container", "energy", "battery");
recipe("battery", "water", "electrolysis");
recipe("life", "planet", "earth (planet)");
recipe("earth (planet)", "star", "sun");
recipe("sun", "plant", "photosynthesis");
recipe("photosynthesis", "plant", "oxygen");
recipe("photosynthesis", "plankton", "phytoplankton");
recipe("sun", "phytoplankton", "oxygen");
recipe("pressure", "plant", "coal");
recipe("coal", "pressure", "diamond");
recipe("hourglass", "philosophy", "time");
recipe("time", "plant", "tree");
recipe("stone", "lake", "ducks and drakes");
recipe("ducks and drakes", "stone", "drakestone");
recipe("ducks and drakes", "rock", "drakestone");
recipe("animal", "dam", "beaver");
recipe("wood", "pressure", "paper");
recipe("paper", "wood", "book");
recipe("book", "idea", "story");
recipe("fire", "wood", "campfire");
recipe("campfire", "smoke", "smoke signal");
recipe("wood", "tool", "wheel");
recipe("wheel", "wood", "cart");
recipe("wood", "water", "boat");
recipe("tree", "fire", "charcoal");
recipe("wood", "corpse", "coffin");
recipe("tree", "house", "treehouse");
recipe("wood", "tree", "stick");
recipe("stick", "fish", "fishing rod");
recipe("fishing rod", "fish", "angler fish");
recipe("stick", "idea", "weapon");
recipe("weapon", "gunpowder", "firearm");
recipe("wood", "wall", "fence");
recipe("wood", "human", "house");
recipe("house", "wood", "log cabin");
recipe("wood", "coal", "pencil");
recipe("wood", "charcoal", "pencil");
recipe("wood", "life", "puppet");
recipe("life", "corpse", "zombie");
recipe("zombie", "science", "necromancy");
recipe("time", "corpse", "skeleton");
recipe("necromancy", "human", "necromancer");
recipe("country", "skeleton", "mexico");
recipe("mexico", "human", "mexican");
recipe("tobacco", "wood", "pipe");
recipe("bird", "wood", "woodpecker");
recipe("wood", "container", "bucket");
recipe("wood", "pencil", "ruler");
recipe("plant", "fire", "tobacco");
recipe("plant", "smoke", "incense");
recipe("tobacco", "paper", "cigarette");
recipe("cigarette", "human", "lung cancer");
recipe("lung cancer", "human", "corpse");
recipe("corpse", "philosophy", "death");
recipe("tobacco", "country", "jamaica");
recipe("jamaica", "human", "jamaican");
recipe("cigarette", "plant", "cannabis");
recipe("country", "cigarette", "cuba");
recipe("cuba", "human", "cuban");
recipe("skeleton", "philosophy", "death");
recipe("philosophy", "human", "philosopher");
recipe("time", "life", "death");
recipe("bone", "corpse", "skeleton");
recipe("skeleton", "light", "x-ray");
recipe("lightbulb", "electricity", "light");
recipe("skeleton", "earth", "fossil");
recipe("skeleton", "rock", "fossil");
recipe("skeleton", "stone", "fossil");
recipe("skeleton", "time", "fossil");
recipe("fossil", "animal", "dinosaur");
recipe("electricity", "corpse", "frankenstein");
recipe("frankenstein", "science", "reanimation");
recipe("corpse", "earth", "grave");
recipe("grave", "grave", "graveyard");
recipe("grave", "necromancy", "zombie");
recipe("grave", "reanimation", "zombie");
recipe("grave", "life", "zombie");
recipe("bird", "corpse", "vulture");
recipe("vulture", "corpse", "skeleton");
recipe("corpse", "stone", "fossil");
recipe("corpse", "rock", "fossil");
recipe("atmosphere", "air", "sky");
recipe("sky", "star", "space");
recipe("space", "human", "astronaut");
recipe("sky", "sun", "day");
recipe("space", "glass", "telescope");
recipe("tree", "tool", "wood");
recipe("cloud", "energy", "storm");
recipe("tool", "woodpecker", "hammer");
recipe("hammer", "boulder", "ore");
recipe("wood", "earth", "plow");
recipe("plow", "earth", "field");
recipe("field", "human", "farmer");
recipe("human", "wood", "tool");
recipe("human", "rock", "tool");
recipe("human", "stone", "tool");
recipe("farmer", "animal", "livestock");
recipe("livestock", "grass", "cow");
recipe("livestock", "cloud", "sheep");
recipe("cloud", "animal", "sheep");
recipe("mud", "animal", "pig");
recipe("mud", "livestock", "pig");
recipe("livestock", "bird", "chicken");
recipe("sun", "day", "morning");
recipe("morning", "bird", "rooster");
recipe("morning", "chicken", "rooster");
recipe("cow", "water", "milk");
recipe("cow", "farmer", "milk");
recipe("cow", "house", "barn");
recipe("sea", "cow", "manatee");
recipe("cow", "human", "minotaur");
recipe("milk", "time", "cheese");
recipe("cheese", "animal", "mouse");
recipe("mouse", "sky", "bat");
recipe("bat", "house", "cave");
recipe("cave", "rock", "ore");
recipe("cow", "mountain", "yak");
recipe("sand", "sand", "desert");
recipe("desert", "cow", "camel");
recipe("human", "human", "love");
recipe("love", "time", "eternal");
recipe("love", "plant", "rose");
recipe("love", "container", "family");
recipe("love", "diamond", "ring");
recipe("ring", "love", "marriage");
recipe("marriage", "human", "wedding");
recipe("continent", "country", "australia");
recipe("australia", "human", "australian");
recipe("australia", "sun", "skin cancer");
recipe("skin cancer", "human", "corpse");
recipe("corpse", "flower", "titan arum");
recipe("plant", "garden", "flower");
recipe("plant", "fence", "hedge");
recipe("garden", "fence", "hedge");
recipe("time", "tool", "clock");
recipe("human", "tool", "engineer");
recipe("tool", "fish", "fishing rod");
recipe("tool", "light", "flashlight");
recipe("tool", "brick", "house");
recipe("tool", "grass", "lawn mower");
recipe("tool", "garden", "trowel");
recipe("grass", "garden", "weed");
recipe("weed", "tool", "weed whacker");
recipe("tool", "cow", "meat");
recipe("tool", "pig", "meat");
recipe("tool", "sheep", "wool");
recipe("clay", "tool", "pottery");
recipe("space", "water", "ice");
recipe("rain", "human", "cold");
recipe("cold", "water", "ice");
recipe("ice", "water", "glacier");
recipe("ice", "continent", "antarctica");
recipe("antarctica", "ocean", "arctic");
recipe("stone", "tool", "statue");
recipe("sheep", "plant", "cotton");
recipe("wool", "plant", "cotton");
recipe("cotton", "tool", "thread");
recipe("wool", "tool", "thread");
recipe("rain", "tool", "umbrella");
recipe("pressure", "tool", "boiler");
recipe("steam", "tool", "boiler");
recipe("gunpowder", "tool", "bullet");
recipe("bullet", "firearm", "shell");
recipe("sun", "clock", "sundial");
recipe("thread", "tool", "fabric");
recipe("house", "tool", "factory");
recipe("sun", "rain", "rainbow");
recipe("rainbow", "rainbow", "double rainbow");
recipe("rainbow", "water", "paint");
recipe("paint", "human", "painter");
recipe("rainbow", "sheep", "jeb_");
recipe("pencil", "tool", "mechanical pencil");
recipe("pencil", "paint", "marker");
recipe("paint", "wall", "mural");
recipe("tool", "soil", "field");
recipe("tool", "lightbulb", "flashlight");
recipe("tool", "animal", "human");
recipe("tool", "wheel", "machine");
recipe("tool", "tool", "machine");
recipe("tool", "container", "toolbox");
recipe("boiler", "tool", "container");
recipe("tool", "chicken", "meat");
recipe("life", "stone", "egg");
recipe("egg", "chicken", "paradox");
recipe("tool", "ore", "metal");
recipe("metal", "oxygen", "rust");
recipe("rust", "electrolysis", "iron");
recipe("bird", "meat", "poultry");
recipe("meat", "cow", "beef");
recipe("meat", "pig", "pork");
recipe("metal", "thread", "needle");
recipe("fire", "egg", "omelette");
recipe("water", "double rainbow", "paint");
recipe("syringe", "idea", "vaccine");
recipe("storm", "tool", "umbrella");
recipe("animal", "tobacco", "tobacco hornworm");
recipe("tobacco hornworm", "time", "carolina sphinx moth");
recipe("time", "life", "death");
recipe("animal", "milk", "cat");
recipe("cat", "plant", "catnip");
recipe("cat", "flower", "catnip");
recipe("container", "livestock", "barn");
recipe("container", "bird", "birdcage");
recipe("birdcage", "zoo", "aviary");
recipe("birdcage", "ocean", "crab trap");
recipe("birdcage", "sea", "crab trap");
recipe("crab trap", "animal", "crab");
recipe("crab", "tool", "claw");
recipe("crab", "palm", "coconut crab");
recipe("paper", "paper", "paperboard");
recipe("paperboard", "paperboard", "cardboard");
recipe("cardboard", "cardboard", "box");
recipe("cat", "box", "schrödinger's cat");
recipe("schrödinger's cat", "philosophy", "quantum superposition");
recipe("human", "schrödinger's cat", "quantum collapse");
recipe("quantum collapse", "quantum superposition", "choice");
recipe("love", "flower", "rose");
recipe("planet", "acid rain", "venus");
recipe("acid rain", "human", "corpse");
recipe("smoke", "rain", "acid rain");
recipe("planet", "ocean", "neptune");
recipe("planet", "sun", "mercury");
recipe("ring", "planet", "saturn");
recipe("telescope", "space", "celestial body");
recipe("celestial body", "sun", "star");
recipe("celestial body", "earth", "planet");
recipe("celestial body", "earth (planet)", "planet");
recipe("celestial body", "venus", "planet");
recipe("celestial body", "mercury", "planet");
recipe("celestial body", "neptune", "planet");
recipe("celestial body", "saturn", "planet");
recipe("celestial body", "crab", "cancer");
recipe("crab", "constellation", "cancer");
recipe("cancer", "human", "corpse");
recipe("cancer", "science", "disease");
recipe("cancer", "animal", "crab");
recipe("diamond", "container", "safe");
recipe("sun", "flower", "sunflower");
recipe("bird", "antarctica", "penguin");
recipe("tree", "beach", "palm");
recipe("tree", "island", "palm");
recipe("star", "star", "asterism");
recipe("asterism", "asterism", "constellation");
recipe("human", "cold", "illness");
recipe("paint", "science", "colorology");
recipe("colorology", "philosophy", "color");
recipe("color", "coal", "black");
recipe("color", "obsidian", "black");
recipe("color", "grass", "green");
recipe("color", "sky", "blue");
recipe("color", "ocean", "blue");
recipe("color", "zombie", "green");
recipe("color", "cancer", "purple");
recipe("color", "sand", "yellow");
recipe("color", "sun", "yellow");
recipe("color", "neptune", "blue");
recipe("color", "rose", "red");
recipe("color", "ice", "blue");
recipe("color", "mud", "brown");
recipe("earth", "fire", "lava");
recipe("color", "lava", "red");
recipe("color", "wood", "brown");
recipe("human", "choice", "conscience");
recipe("metal", "electricity", "copper");
recipe("color", "copper", "orange");
recipe("orange", "cat", "tabby");
recipe("copper", "lightning", "lightning rod");
recipe("lightning rod", "lightning", "electricity");
recipe("obsidian", "philosophy", "sharp");
recipe("sharp", "metal", "blade");
recipe("blade", "human", "blood");
recipe("color", "blood", "red");
recipe("blood", "needle", "syringe");
recipe("blade", "wood", "axe");
recipe("paper", "blade", "confetti");
recipe("bone", "blade", "claw");
recipe("axe", "blade", "pickaxe");
recipe("pickaxe", "cave", "mineral");
recipe("blade", "cow", "leather");
recipe("blade", "pencil", "pencil sharpener");
recipe("blade", "meat", "knife");
recipe("blade", "grass", "scythe");
recipe("scythe", "death", "grim reaper");
recipe("grim reaper", "human", "death");
recipe("star", "blade", "shuriken");
recipe("blade", "metal", "sword");
recipe("blade", "blade", "scissors");
recipe("scissors", "idea", "cut");
recipe("cut", "sword", "slash");
recipe("sword", "fish", "swordfish");
recipe("bird", "fish", "flying fish");
recipe("color", "light", "vibrant");
recipe("light", "black", "shade");
recipe("shade", "color", "muted");
recipe("venus", "human", "female");
recipe("dust", "planet", "mars");
recipe("mars", "human", "male");
recipe("mars", "volcano", "olympus mons");
recipe("mars", "celestial body", "planet");
recipe("choice", "love", "partner");
recipe("male", "female", "love");
recipe("male", "earth", "adam");
recipe("female", "earth", "eve");
recipe("adam", "garden", "garden of eden");
recipe("garden of eden", "tree", "tree of the knowledge of good and evil");
recipe("color", "cloud", "white");
recipe("ice", "rain", "hail");
recipe("cold", "rain", "snow");
recipe("snow", "human", "snowman");
recipe("snowman", "female", "snowwoman");
recipe("snowwoman", "male", "snowman");
recipe("male", "cow", "bull");
recipe("female", "rose", "carnation");
recipe("tree", "sun", "fruit");
recipe("fruit", "time", "mold");
recipe("mold", "science", "penicillin");
recipe("mold", "wood", "rot");
recipe("flower", "pond", "lily pad");
recipe("lily pad", "animal", "frog");
recipe("fish", "egg", "roe");
recipe("frog", "egg", "frogspawn");
recipe("frogspawn", "time", "tadpole");
recipe("fruit", "meat", "food");
recipe("food", "roe", "caviar");
recipe("science", "air", "gas");
recipe("science", "water", "liquid");
recipe("science", "rock", "solid");
recipe("gas", "planet", "gas giant");
recipe("solid", "planet", "rocky planet");
recipe("liquid", "planet", "hycean planet");
recipe("ice", "planet", "ice giant");
recipe("gas giant", "ice", "ice giant");
recipe("cheese", "sky", "moon");
recipe("moon", "sky", "night");
recipe("day", "moon", "night");
recipe("night", "sun", "day");
recipe("sky", "stone", "moon");
recipe("story", "human", "history");
recipe("story", "country", "history");
recipe("life", "book", "biography");
recipe("book", "human", "author");
recipe("author", "biography", "biographer");
recipe("scientist", "human", "anthropologist");
recipe("anthropologist", "science", "anthropology");
recipe("shuriken", "human", "ninja");
recipe("star", "fish", "starfish");
recipe("monarch", "country", "empire");
recipe("empire", "red", "ussr");
recipe("ussr", "time", "collapse");
recipe("ussr", "ideology", "communism");
recipe("collapse", "boulder", "wreaking ball");
recipe("continent", "australia", "oceania");
recipe("continent", "canada", "north america");
recipe("continent", "jamaica", "north america");
recipe("continent", "cuba", "north america");
recipe("copper", "thread", "wire");
recipe("wire", "copper", "copper wire");
recipe("copper wire", "copper wire", "coil");
recipe("coil", "electricity", "magnet");
recipe("hammer", "tool", "nail");
recipe("nail", "tool", "hammer");
recipe("food", "human", "chef");
recipe("chef", "livestock", "butcher");
recipe("color", "cheese", "yellow");
recipe("machine", "bird", "plane");
recipe("plane", "paper", "paper airplane");
recipe("wheel", "machine", "bicycle");
recipe("pressure", "fossil", "oil");
recipe("bicycle", "machine", "motorcycle");
recipe("motorcycle", "machine", "car");
recipe("car", "oil", "motor oil");
recipe("oil", "country", "saudi arabia");
recipe("saudi arabia", "human", "saudi arabian");
recipe("graveyard", "story", "ghost");
recipe("graveyard", "night", "ghost");
recipe("story", "time", "legend");
recipe("legend", "graveyard", "ghost");
recipe("ghost", "science", "ghostology");
recipe("ghost", "village", "ghosttown");
recipe("ghost", "town", "ghosttown");
recipe("ghost", "human", "possession");
recipe("ghost", "ghost", "spirit");
recipe("ghost", "philosophy", "spirit");
recipe("spirit", "human", "soul");
recipe("ghost", "fabric", "sheet");
recipe("ghost", "fruit", "ghost pepper");
recipe("hearth", "human", "warmth");
recipe("warmth", "science", "heat");
recipe("heat", "fruit", "pepper");
recipe("paint", "black", "ink");
recipe("ink", "fish", "squid");
recipe("squid", "food", "calamari");
recipe("life", "fruit", "lemon");
recipe("orange", "fruit", "orange");
recipe("country", "fabric", "flag");
recipe("flag", "science", "vexillology");
recipe("ghostology", "human", "ghostologist");
recipe("vexillology", "human", "vexillologist");
recipe("communism", "human", "communist");
recipe("communist", "ussr", "joseph stalin");
recipe("joseph stalin", "ideology", "stalinism");
recipe("stalinism", "human", "stalinist");
recipe("atmosphere", "machine", "rocket");
recipe("rocket", "space", "spaceship");
recipe("telescope", "human", "astronomer");
recipe("astronomer", "science", "astronomy");
recipe("space", "science", "astronomy");
recipe("soil", "animal", "worm");
recipe("worm", "idea", "geophagia");
recipe("worm", "fruit", "apple");
recipe("apple", "idea", "gravity");
recipe("ocean", "moon", "tide");
recipe("night", "moon", "afternoon");
recipe("morning", "afternoon", "noon");
recipe("noon", "time", "12:00");
recipe("12:00", "night", "midnight");
recipe("midnight", "ocean", "midnight ocean");
recipe("sun", "light", "sunlight");
recipe("gravity", "pressure", "blackhole");
recipe("oxygen", "human", "carbon dioxide");
recipe("carbon dioxide", "plant", "oxygen");
recipe("time", "history", "past");
recipe("past", "human", "monkey");
recipe("monkey", "fruit", "banana");
recipe("glass", "sea", "sea glass");
recipe("glass", "house", "window");
recipe("mexico", "food", "taco");
recipe("past", "ussr", "russian empire");
recipe("russian empire", "past", "tsardom of russia");
recipe("fruit", "water", "juice");
recipe("juice", "time", "alcohol");
recipe("juice", "cold", "popsicle");
recipe("juice", "ice", "popsicle");
recipe("juice", "carbon dioxide", "soda");
recipe("soda", "science", "carbonation");
recipe("carbonation", "juice", "soda");
recipe("water", "heat", "boil");
recipe("boil", "juice", "sugar");
recipe("boil", "water", "steam");
recipe("boil", "sugar", "caramel");
recipe("human", "alcohol", "drunk");
recipe("alcohol", "carbonation", "champagne");
recipe("alcohol", "carbon dioxide", "champagne");
recipe("alcohol", "rose", "perfume");
recipe("alcohol", "flower", "perfume");
recipe("fruit", "alcohol", "wine");
recipe("liquid", "container", "bottle");
recipe("alcohol", "container", "bottle");
recipe("dust", "color", "chalk");
recipe("dust", "white", "chalk");
recipe("stick", "plant", "leaf");
recipe("time", "sun", "summer");
recipe("summer", "snow", "winter");
recipe("summer", "flower", "spring");
recipe("spring", "leaf", "autumn");
recipe("mountain", "rain", "river");
recipe("river", "philosophy", "motion");
recipe("motion", "gravity", "projectile motion");
recipe("motion", "air", "wind");
recipe("motion", "atmosphere", "wind");
recipe("wind", "dust", "dust devil");
recipe("wind", "wind", "tornado");
recipe("tornado", "dust", "dust devil");
recipe("tornado", "water", "cyclone");
recipe("tornado", "ocean", "hurricane");
recipe("wind", "snow", "blizzard");
recipe("sand", "wind", "sandstorm");
recipe("sandstorm", "snow", "blizzard");
recipe("blizzard", "sand", "sandstorm");
recipe("beach", "wind", "dune");
recipe("leaf", "wind", "abscission");
recipe("wind", "plant", "dandelion");
recipe("planet", "hurricane", "neptune");
recipe("wood", "wind", "flute");
recipe("paper", "wind", "kite");
recipe("tree", "wind", "abscission");
recipe("boat", "wind", "sailboat");
recipe("stone", "wind", "sand");
recipe("sea", "wind", "wave");
recipe("ocean", "wind", "wave");
recipe("wave", "air", "sound");
recipe("air", "space", "vacuum");
recipe("house", "wind", "windmill");
recipe("windmill", "metal", "wind turbine");
recipe("flower", "wind", "pollen");
recipe("pollen", "human", "allergy");
recipe("desert", "wind", "sandstorm");
recipe("wind", "electricity", "wind turbine");
recipe("wind turbine", "wind", "electricity");
recipe("windmill", "country", "netherlands");
recipe("netherlands", "continent", "europe");
recipe("netherlands", "human", "dutch");
recipe("plane", "blade", "helicopter");
recipe("windmill", "electricity", "wind turbine");
recipe("sunflower", "windmill", "oil");
recipe("farmer", "plant", "wheat");
recipe("wheat", "windmill", "flour");
recipe("wheat", "alcohol", "beer");
recipe("beer", "human", "drunk");
recipe("wine", "human", "drunk");
recipe("wheat", "milk", "cereal");
recipe("wheat", "stone", "flour");
recipe("blade", "wheat", "scythe");
recipe("wheat", "house", "silo");
recipe("wheat", "container", "silo");
recipe("wheat", "barn", "silo");
recipe("machine", "windmill", "wind turbine");
recipe("sea", "plane", "seaplane");
recipe("ocean", "plane", "seaplane");
recipe("crab", "science", "carcinization");
recipe("corpse", "vulture", "bone");
recipe("bone", "chicken", "chicken wing");
recipe("bone", "flute", "gudi");
recipe("flute", "human", "flutist");
recipe("gudi", "human", "gudi player");
recipe("flute", "wind", "music");
recipe("gudi", "wind", "music");
recipe("bone", "bone", "skeleton");
recipe("bone", "sea", "coral");
recipe("bone", "ocean", "coral");
recipe("bone", "time", "fossil");
recipe("bone", "earth", "fossil");
recipe("bone", "rock", "fossil");
recipe("bone", "rock", "fossil");
