recipe("water", "water", "puddle");
recipe("water", "fire", "steam");
recipe("water", "air", "mist");
recipe("water", "earth", "mud");
recipe("puddle", "puddle", "pool");
recipe("mud", "earth", "clay");
recipe("clay", "fire", "brick");
recipe("earth", "mud", "soil");
recipe("earth", "earth", "rock");
recipe("rock", "fire", "lava");
recipe("pool", "pool", "pond");
recipe("pond", "pond", "lake");
recipe("lake", "lake", "bay");
recipe("bay", "bay", "sea");
recipe("sea", "sea", "ocean");
recipe("air", "mist", "cloud");
recipe("rock", "rock", "boulder");
recipe("boulder", "boulder", "hill");
recipe("hill", "hill", "mountain");
recipe("mountain", "lava", "volcano");
recipe("mountain", "mountain", "mountain range");
recipe("mountain range", "mountain range", "continent");
recipe("continent", "ocean", "planet");
recipe("brick", "brick", "wall");
recipe("wall", "wall", "house");
recipe("house", "house", "street");
recipe("street", "street", "neighborhood");
recipe("neighborhood", "neighborhood", "village");
recipe("village", "village", "town");
recipe("town", "town", "city");
recipe("city", "city", "metropolis");
recipe("metropolis", "metropolis", "megacity");
recipe("megacity", "megacity", "conurbation");
recipe("conurbation", "conurbation", "megaregion");
recipe("megaregion", "megaregion", "eperopolis");
recipe("eperopolis", "eperopolis", "ecumenopolis");
recipe("cloud", "water", "rain");
recipe("air", "air", "pressure");
recipe("lava", "water", "obsidian");
recipe("volcano", "water", "geyser");
recipe("volcano", "ocean", "island");
recipe("island", "island", "archipelago");
recipe("continent", "continent", "supercontinent");
recipe("planet", "planet", "solar system");
recipe("house", "fire", "hearth");
recipe("village", "wall", "fort");
recipe("fort", "house", "fortress");
recipe("fortress", "fortress", "castle");
recipe("castle", "castle", "palace");
recipe("hill", "water", "valley");
recipe("mountain", "lake", "alpine lake");
recipe("mountain range", "sea", "fjord");
recipe("mist", "mist", "fog");
recipe("fog", "fog", "cloud");
recipe("steam", "fire", "smoke");
recipe("soil", "house", "garden");
